//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Библиотека
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент_Книга
    {
        public int ID_Клиент { get; set; }
        public int ID_Книга { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Дата_возврата { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Дата_выдачи { get; set; }
        public int ID_Выдачи { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Книги Книги { get; set; }
    }
}
